### PR TITLE
wtf is a "sonic 3 good future" and why is it here

### PR DESCRIPTION
**Pull request by blu32x**

### CODE REVIEW

**Comment by Stumpedlogs** [comment]
sonic 3 good future? must be the wind

**Comment by SAMPL7790** [comment]
https://gamebanana.com/projects/36076

**Comment by Arsenij-Barsukov** [comment]
sonic 3 good future it's mine project (i'm telejaba)

**Comment by Stumpedlogs** [comment]
also somebody please fufill the pull requests holy shit

**Pull request merged**
